<project name="Adempiere Build Travis" default="build" basedir=".">
    <description>
        Building ADempiere
        by
        Yamel Senih
        http://www.erpya.com
    </description>
  <!-- set global properties for this build -->
  <property name="env_directory" location="install/build/Adempiere/utils"/>
  <property name="AD_directory" location="install/build/Adempiere"/>
  <property name="adempiere_build" location="utils_dev/build.xml"/>
  <property name="myEnvironment_CI" location="install/build/Adempiere/utils/myEnvironment_CI.sh"/>
  <property name="myEnvironment" location="install/build/Adempiere/utils/myEnvironment.sh"/>
  <property name="RUN_DBRestore" location="install/build/Adempiere/utils/RUN_DBRestore.sh"/>
  <property name="RUN_DBExport" location="install/build/Adempiere/utils/RUN_DBExport.sh"/>
  <property name="RUN_ExportReference" location="install/build/Adempiere/utils/RUN_ExportReference.sh"/>
  <property name="RUN_ImportAdempiere" location="install/build/Adempiere/utils/RUN_ImportAdempiere.sh"/>
  <property name="RUN_MigrateXML" location="install/build/Adempiere/utils/RUN_MigrateXML.sh"/>
  <property name="RUN_silentsetup" location="install/build/Adempiere/RUN_silentsetup.sh"/>
  <property name="AdempierePropertiesFrom" location="install/build/Adempiere/utils/adempiereProperties_CI.properties"/>
  <property name="AdempierePropertiesTo" location="install/build/Adempiere/Adempiere.properties"/>
  <property name="myDBcopyTemplate" location="install/build/Adempiere/utils/myDBcopyTemplate.sh"/>
  <property name="myDBcopy" location="install/build/Adempiere/utils/myDBcopy.sh"/>
  
  
  
  <target name="build">
        <echo message="Building ADempiere"/>
	<ant antfile="${adempiere_build}" target="build"/>
	
	<echo message="Deploy ADempiere"/>
	<chmod dir="${AD_directory}" perm="ugo+rx" includes="**/*.sh"/>
	<chmod dir="${AD_directory}/data" perm="ugo+rx" includes="**/*.dmp"/>
	<chmod dir="${env_directory}" perm="ugo+rx" includes="**/*.sh"/>
	<chmod dir="${env_directory}/PostgreSQL" perm="ugo+rx" includes="**/*.sh"/>
	<echo message="Copy myEnvironment_CI to myEnvironment"/>
  	<copy file="${myEnvironment_CI}"
			tofile="${myEnvironment}" filtering="yes" overwrite="yes" />
  	
	
	<echo message="Copy myDBcopyTemplate to myDBcopy"/>
  	<copy file="${myDBcopyTemplate}"
			tofile="${myDBcopy}" filtering="yes" overwrite="yes" />
	
  	<echo message="Copy myEnvironment_CI to myEnvironment"/>
  	<copy file="${AdempierePropertiesFrom}"
			tofile="${AdempierePropertiesTo}" filtering="yes" overwrite="yes" />
	
  	<echo message="Run Import Adempiere"/>
  	<exec dir="${env_directory}" executable="/bin/bash" failonerror="true">
    	<arg value="${RUN_ImportAdempiere}"/>
  	</exec>
  	
  	<echo message="Run DB Restore Adempiere"/>
	<exec dir="${env_directory}" executable="/bin/bash" failonerror="true">
    	<arg value="${RUN_DBRestore}"/>
  	</exec>
  	
	<!--<echo message="Run Migrate XML"/>
	<exec dir="${AD_directory}" executable="/bin/bash" failonerror="true">
    	<arg value="${RUN_MigrateXML}"/>
  	</exec>
	-->
	<echo message="Run Export Database"/>
	<exec dir="${env_directory}" executable="/bin/bash" failonerror="true">
    	<arg value="${RUN_ExportReference}"/>
  	</exec>
	  
	<echo message="Installing ADempiere"/>
	<ant antfile="${adempiere_build}" target="install"/>
	  
	<!--<echo message="Run Export Database"/>
	<exec dir="${env_directory}" executable="/bin/bash" failonerror="true">
    	<arg value="${RUN_DBExport}"/>
  	</exec>-->
  </target>
</project>
